/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sobad;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

public class App {
    public static void main(String[] args) {
    }
}
